#!/bin/bash

#1.  Check if devkit.verssion was changed in the lasts pulll
# "ORIG_HEAD" is where you were, "HEAD" is where you are now
if [ "$CHANGED_FILE" ]; then
    echo "detected change in devkit.version.  Generating new S3 link..."

    BUCKET="devkitassets"
    FILE_KEY="devkit.rar"

    #1.  Generate the URL using AWS CLI
    URL=$(aws s3 presign s3://$BUCKET/$FILE_KEY --expires-in 604800)

    #2.  Save it to a file in the project directory
    echo $URL > "./$FILE_KEY"
    echo "S3 link updataed successfully"
else
    echo "No change to devkit.version.  Sskipping S3 link update."
fi