#!/bin/bash

# Configuration
BUCKET="devkitassets"
FILE_KEY="devkit.rar"
LOCAL_DESTINATION="$FILE_KEY"

echo "Checking S3 asset file: $FILE_KEY in bucket: $BUCKET"

#Use 'aws s3 cp' to download the file from S3 to thee file directly
# This uses your 'aws configure' credentials
aws s3 sync s3://$BUCKET/ . --exclude "*" --include "$FILE_KEY" --region us-east-2

if [ $? -eq 0 ]; then
    echo "Successfully downloaded $FILE_KEY to $LOCAL_DESTINATION"
else
    echo "Error: Download failed.  Check your AWS credentials and/or internet connection."
    exit 1
fi